<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-4RCGPP9C" failures="1" tests="6" name="Com.Ecommerce.TestCases.TC_Login_Page" time="111.033" errors="0" timestamp="2024-03-21T09:11:44 IST" skipped="4">
  <testcase classname="Com.Ecommerce.TestCases.TC_Login_Page" name="LoginPage" time="19.436">
    <skipped/>
  </testcase> <!-- LoginPage -->
  <testcase classname="Com.Ecommerce.TestCases.TC_Login_Page" name="LoginPage" time="15.704">
    <skipped/>
  </testcase> <!-- LoginPage -->
  <testcase classname="Com.Ecommerce.TestCases.TC_Login_Page" name="LoginPage" time="13.379">
    <skipped/>
  </testcase> <!-- LoginPage -->
  <testcase classname="Com.Ecommerce.TestCases.TC_Login_Page" name="LoginPage" time="25.363">
    <skipped/>
  </testcase> <!-- LoginPage -->
  <testcase classname="Com.Ecommerce.TestCases.TC_Login_Page" name="LoginPage" time="20.089"/>
  <testcase classname="Com.Ecommerce.TestCases.TC_Login_Page" name="LoginPage" time="17.062">
    <failure message="expected [nopCommerce demo store] but found [nopCommerce demo store. Login]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [nopCommerce demo store] but found [nopCommerce demo store. Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Com.Ecommerce.TestCases.TC_Login_Page.LoginPage(TC_Login_Page.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- LoginPage -->
</testsuite> <!-- Com.Ecommerce.TestCases.TC_Login_Page -->
